arquivoOutubro = './Arquivos/2019-Oct.csv'
arquivoNovembro = './Arquivos/2019-Nov.csv'
arquivoDezembro = './Arquivos/2019-Dec.csv'
arquivoJaneiro = './Arquivos/2020-Jan.csv'
arquivoFevereiro = './Arquivos/2020-Feb.csv'
arquivoMarco = './Arquivos/2020-Mar.csv'
arquivoAbril = './Arquivos/2020-Apr.csv'